// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxsfjofnyzwhlqxavdpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4c2Zqb2ZueXp3aGxxeGF2ZHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTc3MzMsImV4cCI6MjA3MTA5MzczM30.Vv5-89XMMLGM3pPYrN0juT07wl21GBsiHnDitZTKgQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});